### ISSUE TITLE
Form not cleared after submit

### ISSUE THREAD

**Issue by 0xAl3xH** [dianezhou96/lululedger#29] opened 2023-06-18 21:00 UTC
I might have introduced a bug where the form isn't being cleared after adding to cart?

**Comment by 0xAl3xH** [comment] 2023-06-18 21:24
is this to support editing feature? if so it needs reflect the total quantity of each item in the cart

**Comment by dianezhou96** [comment] 2023-06-19 00:51
Duplicate of #31

**Closed by dianezhou96** 2023-06-19 00:51 UTC
Labels: bug
